### ISSUE TITLE
屏蔽群组通知

### ISSUE THREAD

**Issue by phperfan** [code4thought/dingtalk-notifier#1]
因为接入了监控的消息， 所以希望可以屏蔽一部分消息推送。

现在设置了免打扰也会有消息通知

**Comment by haipengpan** [comment]
这个提议很好，我当时急于实现，没有考虑这么完善，稍后会加上

**Comment by haipengpan** [comment]
Solved!

88a7edd9dfde17dc2b7567012b203ff1d20856ce
